import Foundation
import TillyCore

enum KeypadKey: Equatable, Sendable {
    case digit(Int), decimal, delete
}

/// The draft as it was when an existing charge opened, and where that charge sits in its
/// bill. Comparing the draft's live fields against these is how the editor knows what
/// changed and, from that, what saving means.
struct EditBaseline: Equatable, Sendable {
    let digits: String
    let name: String
    let date: Date // the charge's effective date, start of day
    let interval: Int
    let unit: RecurrenceUnit
    let paymentCount: Int? // the whole bill's; nil = no end
    let categoryID: UUID?
    let ruleAnchor: Date // anchor of the record this charge belongs to
    let paymentsBeforeRule: Int // charges generated by the series' earlier records
    let chargeIndex: Int // this charge's index within its record, 0-based
}

/// Which of the draft's fields differ from its `EditBaseline`. All false when the draft
/// isn't editing anything.
struct DraftChanges: Equatable, Sendable {
    var amount = false
    var date = false
    var name = false
    var category = false
    var repeatRule = false
    var paymentCount = false

    var any: Bool { amount || date || name || category || repeatRule || paymentCount }
}

/// What ✓ means for an edit, from `ExpenseDraft.saveIntent(hasLaterCharge:)`.
enum SaveIntent: Equatable, Sendable {
    case nothing, askScope, thisCharge, futureCharges, wholeBill
}

/// Everything the expense editor is holding before Save, as a plain value so the rules of
/// entry are tested without a view. The amount is kept as typed text (`digits`, always with
/// "." for the point) so a trailing decimal survives mid-entry; the locale only renders it.
struct ExpenseDraft: Equatable, Sendable {
    static let maxWholeDigits = 7
    static let maxDecimals = 2

    var digits: String = ""
    var name: String = ""
    var date: Date // start of day
    var interval: Int = 1 // 1...30
    var unit: RecurrenceUnit = .month
    var paymentCount: Int? = nil // nil = no end; otherwise 2...120
    var categoryID: UUID? = nil
    var baseline: EditBaseline? = nil

    init(today: Date, calendar: Calendar) {
        self.date = calendar.startOfDay(for: today)
    }

    /// Copies every field from the baseline, so the editor opens showing exactly the charge
    /// as it stands, with nothing yet counted as changed.
    init(editing baseline: EditBaseline) {
        self.digits = baseline.digits
        self.name = baseline.name
        self.date = baseline.date
        self.interval = baseline.interval
        self.unit = baseline.unit
        self.paymentCount = baseline.paymentCount
        self.categoryID = baseline.categoryID
        self.baseline = baseline
    }

    // MARK: Keypad

    mutating func press(_ key: KeypadKey) {
        switch key {
        case .digit(let digit):
            guard (0...9).contains(digit) else { return }
            if digits == "0" {
                digits = String(digit)
            } else if canAppendDigit {
                digits.append(String(digit))
            }
        case .decimal:
            guard !digits.contains(".") else { return }
            digits = digits.isEmpty ? "0." : digits + "."
        case .delete:
            digits = String(digits.dropLast())
        }
    }

    private var canAppendDigit: Bool {
        let parts = digits.split(separator: ".", maxSplits: 1, omittingEmptySubsequences: false)
        if parts.count == 2 {
            return parts[1].count < Self.maxDecimals
        }
        return digits.count < Self.maxWholeDigits
    }

    // MARK: Meaning

    /// `nil` when empty or zero.
    var amount: Decimal? {
        guard let value = Self.numericValue(digits), value > 0 else { return nil }
        return value
    }

    /// Non-empty and parses to zero — the free-month case `amount` deliberately excludes.
    var isZero: Bool {
        Self.numericValue(digits) == 0
    }

    private static func numericValue(_ digits: String) -> Decimal? {
        let trimmed = digits.hasSuffix(".") ? String(digits.dropLast()) : digits
        guard !trimmed.isEmpty else { return nil }
        return Decimal(string: trimmed, locale: Locale(identifier: "en_US_POSIX"))
    }

    /// Amount, name and category are required to add a charge. Editing relaxes the amount:
    /// zero is an ordinary amount for one free charge, but not for a whole rule newly set to
    /// zero, so a repeat change together with zero stays invalid.
    func isValid(categoryExists: (UUID) -> Bool) -> Bool {
        let amountOK = amount != nil || (baseline != nil && isZero && !changes.repeatRule)
        guard amountOK,
              !name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              let categoryID else { return false }
        return categoryExists(categoryID)
    }

    /// Which fields differ from `baseline`; all false when there isn't one. Name is compared
    /// trimmed, so trailing whitespace alone isn't a change. Amount compares numeric value,
    /// not the typed text, so retyping the same amount — even spelled differently — isn't one.
    var changes: DraftChanges {
        guard let baseline else { return DraftChanges() }
        var result = DraftChanges()
        result.amount = Self.numericValue(digits) != Self.numericValue(baseline.digits)
        result.date = date != baseline.date
        result.name = name.trimmingCharacters(in: .whitespacesAndNewlines)
            != baseline.name.trimmingCharacters(in: .whitespacesAndNewlines)
        result.category = categoryID != baseline.categoryID
        result.repeatRule = interval != baseline.interval || unit != baseline.unit
        result.paymentCount = paymentCount != baseline.paymentCount
        return result
    }

    /// The fewest payments a count can end at: the open charge itself, so the wheel never
    /// offers an end before it.
    var minimumPaymentCount: Int {
        guard let baseline else { return 2 }
        return max(2, baseline.paymentsBeforeRule + baseline.chargeIndex + 1)
    }

    /// What ✓ means, in order: nothing changed; a repeat change always starts future charges,
    /// without asking; zero paired with an amount change is one free charge, saved alone
    /// without asking; any other amount or date change asks when a later charge exists,
    /// otherwise it's the only charge there is to save; anything else (name, category, count)
    /// belongs to the whole bill.
    func saveIntent(hasLaterCharge: Bool) -> SaveIntent {
        let changes = self.changes
        guard changes.any else { return .nothing }
        if changes.repeatRule { return .futureCharges }
        if isZero && changes.amount { return .thisCharge }
        if changes.amount || changes.date { return hasLaterCharge ? .askScope : .thisCharge }
        return .wholeBill
    }

    /// Strictly after today.
    func isFuture(today: Date, calendar: Calendar) -> Bool {
        date > calendar.startOfDay(for: today)
    }

    func rule(calendar: Calendar) -> RecurrenceRule {
        RecurrenceRule(
            interval: interval,
            unit: unit,
            anchorDate: date,
            endDate: lastPaymentDate(calendar: calendar)
        )
    }

    /// The date of the final payment, from the engine, when a count is set. `paymentCount`
    /// counts the whole bill, so when editing, the payment it lands on has to be found
    /// relative to whichever record actually generates it:
    /// - When the repeat and date are exactly as they opened, this record's own rule still
    ///   covers the whole count; the last payment is `paymentCount` minus what the series'
    ///   earlier records already made, anchored where this record always was.
    /// - Otherwise the charge itself starts a new rule (a "future charges" split): the last
    ///   payment is `paymentCount` minus the earlier records' charges and this record's own
    ///   charges before the open one, anchored on the charge's (possibly new) date.
    func lastPaymentDate(calendar: Calendar) -> Date? {
        guard let paymentCount else { return nil }
        guard let baseline else {
            let open = RecurrenceRule(interval: interval, unit: unit, anchorDate: date)
            return RecurrenceEngine.date(ofPayment: max(1, paymentCount) - 1, for: open, calendar: calendar)
        }
        let repeatUnchanged = interval == baseline.interval && unit == baseline.unit && date == baseline.date
        if repeatUnchanged {
            let rule = RecurrenceRule(interval: interval, unit: unit, anchorDate: baseline.ruleAnchor)
            let index = paymentCount - baseline.paymentsBeforeRule - 1
            return RecurrenceEngine.date(ofPayment: index, for: rule, calendar: calendar)
        }
        let rule = RecurrenceRule(interval: interval, unit: unit, anchorDate: date)
        let index = paymentCount - baseline.paymentsBeforeRule - baseline.chargeIndex - 1
        return RecurrenceEngine.date(ofPayment: index, for: rule, calendar: calendar)
    }

    // MARK: Labels

    /// "950" for a whole amount, "74.1" for one decimal, "12.5" for a trailing zero dropped —
    /// the keypad's own text for a stored amount, so opening a charge shows what it would
    /// look like freshly typed.
    static func digits(for amount: Decimal) -> String {
        var rounded = Decimal()
        var value = amount
        NSDecimalRound(&rounded, &value, maxDecimals, .plain)
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.usesGroupingSeparator = false
        formatter.minimumFractionDigits = 0
        formatter.maximumFractionDigits = maxDecimals
        return formatter.string(from: rounded as NSDecimalNumber) ?? "\(rounded)"
    }

    /// "€0" when empty, "€1,250.5" mid-entry. The currency and separators are the locale's.
    func amountText(locale: Locale) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.locale = locale

        let parts = digits.split(separator: ".", maxSplits: 1, omittingEmptySubsequences: false)
        let whole = parts.first.map(String.init) ?? ""
        let fraction = parts.count == 2 ? String(parts[1]) : ""
        formatter.minimumFractionDigits = fraction.count
        formatter.maximumFractionDigits = fraction.count
        formatter.alwaysShowsDecimalSeparator = digits.contains(".")

        let value = Decimal(string: whole.isEmpty ? "0" : whole + (fraction.isEmpty ? "" : "." + fraction),
                            locale: Locale(identifier: "en_US_POSIX")) ?? 0
        return formatter.string(from: value as NSDecimalNumber) ?? digits
    }

    /// "Oct 31", never a year.
    func dateLabel(calendar: Calendar, locale: Locale) -> String {
        let formatter = DateFormatter()
        formatter.calendar = calendar
        formatter.timeZone = calendar.timeZone
        formatter.locale = locale
        formatter.setLocalizedDateFormatFromTemplate("MMMd")
        return formatter.string(from: date)
    }

    /// "Monthly", "3 months", or "05/27" once the bill ends.
    func repeatLabel(calendar: Calendar, locale: Locale) -> String {
        if let last = lastPaymentDate(calendar: calendar) {
            let formatter = DateFormatter()
            formatter.calendar = calendar
            formatter.timeZone = calendar.timeZone
            formatter.locale = locale
            formatter.dateFormat = "MM/yy"
            return formatter.string(from: last)
        }
        if interval == 1 {
            switch unit {
            case .day: return "Daily"
            case .week: return "Weekly"
            case .month: return "Monthly"
            case .year: return "Yearly"
            }
        }
        return "\(interval) \(unit.rawValue)s"
    }

    /// "Last payment Sep 30, 2027"; `nil` without a count.
    func lastPaymentCaption(calendar: Calendar, locale: Locale) -> String? {
        guard let last = lastPaymentDate(calendar: calendar) else { return nil }
        let formatter = DateFormatter()
        formatter.calendar = calendar
        formatter.timeZone = calendar.timeZone
        formatter.locale = locale
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        return "Last payment \(formatter.string(from: last))"
    }
}

enum EmojiInput {
    /// The last emoji character in `text`, or `nil`. A `Character` is a whole grapheme
    /// cluster, so flags, skin tones and joined sequences arrive in one piece.
    static func emoji(from text: String) -> String? {
        text.reversed().first(where: isEmoji).map(String.init)
    }

    private static func isEmoji(_ character: Character) -> Bool {
        let scalars = character.unicodeScalars
        // Emoji presentation, or an explicit variation selector, makes it an emoji outright.
        if scalars.contains(where: { $0.value == 0xFE0F || $0.properties.isEmojiPresentation }) {
            return true
        }
        // Digits, "#" and "*" carry the emoji property as keycap bases, and so do a few
        // symbols below U+238C ("©"); none of those is an emoji without a selector.
        guard let first = scalars.first else { return false }
        return first.properties.isEmoji && first.value > 0x238C
    }
}
